### PR TITLE
Removed git show filter to avoid empty list errors

### PR DESCRIPTION
**Pull request by jimbudarz**
Any filtering on `git show` can result in an empty list of changed files, and then a failure of the check. To include more types of commits, the only _ignored_ files will be deleted files (hence the lower-case `d`).
Addresses Issue #31

### CODE REVIEW

**Comment by jimbudarz** [comment]
This doesn't resolve the issue entirely, and can still result in an error if the commit in question contains _only_ the deletion of a single file.

**Comment by jimbudarz** [comment]
@merill Do you think this is worth incorporating?

**Comment by cblomart** [comment]
@jimbudarz Thanks for the updated. For information i will also look at the analyser handling of empty lists. If there is nothing changed in the content it makes sense not to check any files and most importantly not fail the check.

**Comment by merill** [comment]
Thanks a lot @jimbudarz for the PR! Apologies for my tardiness.

**Pull request merged**
